# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fhswiftui',
                'doc_host': 'https://thechandru.github.io',
                'git_url': 'https://github.com/thechandru/fhswiftui',
                'lib_path': 'fhswiftui'},
  'syms': {'fhswiftui.core': {'fhswiftui.core.foo': ('core.html#foo', 'fhswiftui/core.py')}}}
