"""API for helpers, layout components, UI components, and style modifiers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['bc_link', 'tw_scr', 'fh_swiftui_hdrs', 'IncludeColors', 'mk_previewer']

# %% ../nbs/00_core.ipynb 7
from fastcore.utils import *
from fasthtml.common import *
import fasthtml.components as fh
from fasthtml.jupyter import *

# %% ../nbs/00_core.ipynb 8
def _def_colors():
    base = ["primary","secondary","accent","muted","card","popover"]
    return base+[f"{o}-foreground" for o in base]+["background","foreground","destructive","ring","input","border"]
    

# %% ../nbs/00_core.ipynb 10
# #| export
# def IncludeColors(
#     colors:list=None,  # List of additional Tailwind color names to include (e.g. ['red-500', 'blue-300'])
#     append:bool=True,  # Append to default theme colors; set False to replace all defaults
# ) -> Div:
#     "Include additional colors that will be available via Tailwind utility classes on the page"
#     from itertools import product
#     if not colors: colors = []
#     # Prefixes for color utilities: border sides (l,r,t,b), backgrounds, text, and borders
#     pr = [f"border-{o}" for o in "lrtb"] + ["bg", "text", "border"]
#     # Generate hidden div with all color class combinations to ensure they're included in build
#     return Div(cls=f"hidden {' '.join(f'{p}-{c}' for p,c in product(pr, _def_colors() + colors if append else colors))}")

# %% ../nbs/00_core.ipynb 13
def IncludeColors(
    colors:list=None,  # Tailwind color names to include (e.g. ['red-500', 'blue-300', 'emerald-400'])
    append:bool=True,  # If True, append to default theme colors; if False, replace all defaults
) -> Div: # Hidden div element with color utility classes to ensure they're included in Tailwind build
    "Include additional colors that will be available via Tailwind utility classes on the page"
    from itertools import product
    if not colors: colors = []
    # Utility prefixes: border sides (l,r,t,b), backgrounds, text, and general borders
    pr = [f"border-{o}" for o in "lrtb"] + ["bg", "text", "border"]
    # Combine prefixes with all colors (default theme colors + user colors, or just user colors)
    all_colors = _def_colors() + colors if append else colors
    # Generate hidden div with all color class combinations to force Tailwind to include them
    return Div(cls=f"hidden {' '.join(f'{p}-{c}' for p,c in product(pr, all_colors))}")

# %% ../nbs/00_core.ipynb 14
# enable basecoat and tailwind; add useful default colors
bc_link = Link(rel='stylesheet', href='https://cdn.jsdelivr.net/npm/basecoat-css@latest/dist/basecoat.cdn.min.css')
tw_scr = Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4')

fh_swiftui_hdrs = (bc_link,tw_scr,IncludeColors())


# %% ../nbs/00_core.ipynb 16
def mk_previewer(app=None,hdrs=None,cls=f'max-w-lg'):
    xcls = cls
    if not app: app=FastHTML(hdrs=fh_swiftui_hdrs)
    def p(*c, cls='', **kw):
        return HTMX(Div(cls=f'{xcls} {cls}')(*c), app=app, host=None, port=None, **kw)
    return p

# Based completely on: https://answerdotai.github.io/fhdaisy/core.html#mk_previewer

# %% ../nbs/00_core.ipynb 22
@patch
def append_classes(
    self:FT, # the tag
    *c       # list of classes
):
    "Append css classes to the FastTag element"
    self.attrs["class"] = " ".join(f"{self.attrs.get('class','')} {' '.join(c)}".split())
    return self

# %% ../nbs/00_core.ipynb 24
@patch
def padding(
    self:FT,     # The FastTag element to modify
    **kw         # Padding values: 'all', 'top', 'bottom', 'left', 'right' (Tailwind spacing scale: 0, 1, 2, 4, 8, px, or custom like '[5px]')
):
    "Add padding around the content within the element's bounds. Defaults to p-4 if no arguments provided."
    d = {"top":'t', "bottom":'b', "left":'l', "right":'r'}
    c = [f"p-{kw['all']}"] if "all" in kw else [f"p{d[k]}-{kw[k]}" for k in set(kw) & d.keys()]
    return self.append_classes(*c if c else ["p-4"])

# %% ../nbs/00_core.ipynb 33
@patch
def margin(
    self:FT,        # The FastTag element to modify
    **kw            # Margin values: 'all', 'top', 'bottom', 'left', 'right' (Tailwind spacing scale: 0, 1, 2, 4, 8, px, or custom like '[5px]')
):
    "set margins - space outside the component"
    d = {"top":'t',"bottom":'b',"left":'l',"right":'r'}
    c = [f"m-{kw['all']}"] if "all" in kw else [f"m{d[k]}-{kw[k]}" for k in set(kw) & d.keys()]

    self.append_classes(*c if c else ["m-4"])

    return self

# %% ../nbs/00_core.ipynb 39
@patch
def border(
    self:FT,         # The FastTag element to modify
    width:int=None,  # Border width in Tailwind scale (1, 2, 4, 8) or None for default width
    color:str=None   # Tailwind border color without 'border-' prefix (e.g., 'primary', 'muted', 'gray-300', 'red-500')
):
    "Add a border around the element with optional width and color customization"
    c = ["border"]
    if width: c.append(f"border-{width}")
    if color: c.append(f"border-{color}")
    return self.append_classes(*c)

# %% ../nbs/00_core.ipynb 46
@patch
def corner_radius(
    self:FT,        # The FastTag element to modify
    size:str=None     # Tailwind size suffix (e.g. sm, lg, full)
):   
    "Round the corners for this element"
    return self.append_classes(f"rounded-{size}" if size else "rounded")


# %% ../nbs/00_core.ipynb 54
@patch
def bg(
    self:FT,        # The FastTag element to modify
    color:str       # color of background
): 
    "Set background color"
    return self.append_classes(f"bg-{color}")

# %% ../nbs/00_core.ipynb 55
@patch
def fg(
    self:FT,        # The FastTag element to modify
    color:str       # color of foreground
): 
    "Set foreground color"
    return self.append_classes(f"text-{color}")

# %% ../nbs/00_core.ipynb 62
@patch
def shadow(
    self:FT,    # The FastTag element to modify
    **kw
):
    "Add shadow to element"
    # Parameters:
    # color: shadow color (default 'rgba(0,0,0,0.1)')
    # size: preset size ('sm','md','lg', etc)
    # x,y,blur,spread: offset x, offset y, blur, spread
    if "color" not in kw: kw["color"] = "rgba(0,0,0,0.1)"
    
    if len(kw) == 0: return self.append_classes("shadow")
    if "size" in kw: return self.append_classes(f"shadow-{kw['size']}")
    
    def enc(color,x=0,y=1,blur=3,spread=0,**k2): return f"shadow-[{x}px_{y}px_{blur}px_{spread}px_{color}]"
    return self.append_classes(enc(**kw))

# %% ../nbs/00_core.ipynb 69
@patch
def opacity(
    self:FT,        # The FastTag element to modify
    pct:int=100     # Percent value of opacity as int
):
    "set opacity"
    return self.append_classes(f"opacity-{pct}")

# %% ../nbs/00_core.ipynb 77
@patch
def frame(
    self:FT,            # The FastTag element to modify 
    w=None,             # height of frame
    h=None,             # width of frame
    halign="center",    # horizontal alignment (default: center)
    valign="center"     # vertical alignment (default: center)
):
    "position this element in a frame"
    h_map = {"leading": "justify-start", "center": "justify-center", "trailing": "justify-end"}
    v_map = {"top": "items-start", "center": "items-center", "bottom": "items-end"}
    
    c = ["flex", h_map[halign], v_map[valign]]
    if w: c.append(f"w-{w}")
    if h: c.append(f"h-{h}")
    
    return Div(self).append_classes(*c)

# %% ../nbs/00_core.ipynb 86
@patch
def font(
    self:FT,        # The FastTag element to modify 
    size=None,      # size (e.g. sm, lg, xl, 2xl)
    weight=None     # weight (e.g. light, normal, bold)
):
    "Set default font for this tag"
    c = []
    if size: c.append(f"text-{size}")
    if weight: c.append(f"font-{weight}")
    return self.append_classes(*c)
